apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: argo-test
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: [sh, -c]
    args: 
      - >-
        sleep 36000
    volumeMounts:
    - name: srt
      mountPath: "/srt"
      readOnly: true
  volumes:
  - name: srt
    secret:
      secretName: secret
